# Generated by Django 5.0.2 on 2024-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_author_remove_article_author_name_article_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemetadata',
            name='creationDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
