# Generated by Django 5.0.2 on 2024-04-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_articlemetadata_creationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemetadata',
            name='author',
        ),
        migrations.AddField(
            model_name='articlemetadata',
            name='authors',
            field=models.ManyToManyField(related_name='metadata_authors', to='main.author'),
        ),
    ]
