# Generated by Django 5.2.7 on 2026-03-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_articleembedding_recommendationcache_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleembedding',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='main.article'),
        ),
        migrations.AddConstraint(
            model_name='articleembedding',
            constraint=models.UniqueConstraint(fields=('article', 'model_name'), name='unique_article_model_embedding'),
        ),
    ]
